import{initializeApp}from"https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";import{getFirestore,collection,addDoc,updateDoc,deleteDoc,doc,onSnapshot,query,orderBy,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id);let mods=[],active="All",editing=null;
$("adminOpen").onclick=()=>$("adminModal").classList.remove("hidden");$("adminModal").querySelector("[data-close]").onclick=()=>$("adminModal").classList.add("hidden");$("search").oninput=render;$("sort").onchange=render;
const esc=s=>(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
onSnapshot(query(collection(db,"mods"),orderBy("createdAt","desc")),s=>{mods=s.docs.map(d=>({id:d.id,...d.data()}));cats();render();adminList()},e=>{$("status").textContent="Database connection error. Check Firestore rules/config."});
function cats(){let a=["All",...new Set(mods.map(x=>x.category).filter(Boolean))];$("categories").innerHTML=a.map(c=>`<button class="chip ${active===c?"active":""}" data-c="${esc(c)}">${esc(c)}</button>`).join("");document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{active=b.dataset.c;cats();render()})}
window.__setCategory=(c)=>{active=c;cats();render();document.getElementById("mods").scrollIntoView({behavior:"smooth",block:"start"})}
function render(){let q=$("search").value.toLowerCase(),a=mods.filter(m=>(active==="All"||m.category===active)&&`${m.name} ${m.version} ${m.category} ${m.description}`.toLowerCase().includes(q));if($("sort").value==="name")a.sort((x,y)=>(x.name||"").localeCompare(y.name||""));$("status").textContent=`${a.length} mod${a.length===1?"":"s"}`;$("modGrid").innerHTML=a.map(m=>`<article class="card"><img class="thumb" src="${esc(m.thumbnail||"assets/default.svg")}"><div class="cardBody"><span class="tag">${esc(m.category)} • ${esc(m.version)}</span><h3>${esc(m.name)}</h3><p class="desc">${esc(m.description)}</p><a class="download" href="${esc(m.url)}" target="_blank" rel="noopener">⬇ DOWNLOAD</a></div></article>`).join("")||"<p>No mods found.</p>"}
function adminList(){$("adminList").innerHTML=mods.map(m=>`<div class="adminItem"><img src="${esc(m.thumbnail||"assets/default.svg")}"><div><h4>${esc(m.name)}</h4><p>${esc(m.category)} • ${esc(m.version)}</p></div><div><button class="edit" data-e="${m.id}">Edit</button><button class="delete" data-d="${m.id}">Delete</button></div></div>`).join("")||"<p>No mods yet.</p>";document.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>edit(b.dataset.e));document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>remove(b.dataset.d))}
$("modForm").onsubmit=async e=>{e.preventDefault();if(!auth.currentUser)return alert("Login first");$("saveBtn").disabled=true;try{let d={name:$("name").value.trim(),version:$("version").value.trim(),category:$("category").value,description:$("description").value.trim(),url:$("url").value.trim(),thumbnail:$("thumbnail").value.trim()};if(editing)await updateDoc(doc(db,"mods",editing),d);else{d.createdAt=serverTimestamp();await addDoc(collection(db,"mods"),d)}reset()}catch(err){console.error(err);alert("Save failed. Check Firebase Firestore setup/rules.")}finally{$("saveBtn").disabled=false}};
function edit(id){let m=mods.find(x=>x.id===id);editing=id;$("formTitle").textContent="Edit Mod";$("saveBtn").textContent="Save Changes";$("cancelEdit").classList.remove("hidden");$("name").value=m.name||"";$("version").value=m.version||"";$("category").value=m.category||"Other";$("description").value=m.description||"";$("url").value=m.url||"";$("thumbnail").value=m.thumbnail||""}
$("cancelEdit").onclick=reset;function reset(){editing=null;$("modForm").reset();$("formTitle").textContent="Add Mod";$("saveBtn").textContent="Add Mod";$("cancelEdit").classList.add("hidden")}
async function remove(id){if(!confirm("Delete this mod?"))return;try{await deleteDoc(doc(db,"mods",id))}catch(e){alert("Delete failed")}}
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(e){$("loginError").textContent=e.message}};$("logoutBtn").onclick=()=>signOut(auth);onAuthStateChanged(auth,u=>{$("loginView").classList.toggle("hidden",!!u);$("panelView").classList.toggle("hidden",!u)});
